import "~/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs"

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { Archivo, Poppins } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Baisilic",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const dmSans = Archivo({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-dm-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${dmSans.variable}`}>
        <body className="font-sans">
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <Toaster richColors />
        </body>
      </html>
    </ClerkProvider>

  );
}
