import "~/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs"

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { Inter, Poppins } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Baisilic",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"], // Poids de la police
  variable: "--font-poppins", // Variable CSS pour la police
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="font-sans">
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <Toaster richColors />
        </body>
      </html>
    </ClerkProvider>

  );
}
